# Generated by Django 2.1.5 on 2019-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRankingsMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('movement', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('events', models.IntegerField()),
                ('points', models.FloatField()),
                ('ageGroup', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentFSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age_group', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentITF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host_nation', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(max_length=100)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('surface', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
