# Generated by Django 2.1.5 on 2019-04-13 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRankingsMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('movement', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('events', models.IntegerField()),
                ('points', models.FloatField()),
                ('age_group', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TournamentFSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=1000)),
                ('age_group', models.CharField(max_length=100)),
                ('tournament_venue', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('tournament_description', models.CharField(max_length=1000)),
                ('event_location_url', models.URLField(blank=True, max_length=300, null=True, validators=[django.core.validators.URLValidator])),
                ('coordinator_name', models.CharField(max_length=100, null=True)),
                ('coordinator_contact_number', models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000000, message='Enter a valid phone number'), django.core.validators.MinValueValidator(1000000000, message='Enter a valid phone number')])),
                ('coordinator_email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='TournamentITF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('host_nation', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(max_length=100)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('surface', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
