# Generated by Django 2.1.5 on 2019-03-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerrankingsms',
            old_name='ageGroup',
            new_name='agegroup',
        ),
        migrations.AlterField(
            model_name='playerrankingsms',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
