# Generated by Django 2.1.5 on 2019-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrankingsms',
            name='movement',
            field=models.CharField(max_length=20),
        ),
    ]
