# Generated by Django 2.1.5 on 2019-04-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20190321_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerrankingsms',
            options={'ordering': ['-rank']},
        ),
        migrations.AddField(
            model_name='tournamentfsc',
            name='coordinator_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentfsc',
            name='coordinator_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tournamentfsc',
            name='coordinator_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
