# Generated by Django 2.1.5 on 2019-03-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentitf_host_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentitf',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
