# Generated by Django 2.1.5 on 2019-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20190405_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentfsc',
            name='location_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='playerrankingsms',
            name='agegroup',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='playerrankingsms',
            name='dob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournamentfsc',
            name='date',
            field=models.DateField(),
        ),
    ]
