# Generated by Django 2.1.5 on 2019-04-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20190410_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerrankingsms',
            options={'ordering': ['rank']},
        ),
    ]
