# Generated by Django 2.1.5 on 2019-04-13 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20190410_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentfsc',
            name='coordinator_contact',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000000)]),
        ),
        migrations.AlterField(
            model_name='tournamentfsc',
            name='coordinator_email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='tournamentfsc',
            name='coordinator_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
