# Generated by Django 2.1.5 on 2019-04-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20190413_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentfsc',
            old_name='coordinator_contact',
            new_name='coordinator_contact_number',
        ),
    ]
