# Generated by Django 2.1.5 on 2019-04-13 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20190413_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentitf',
            old_name='name',
            new_name='tournament_name',
        ),
        migrations.AlterField(
            model_name='tournamentfsc',
            name='coordinator_contact_number',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000000, message='Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='tournamentfsc',
            name='event_location_url',
            field=models.URLField(blank=True, max_length=300, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
