# Generated by Django 2.1.5 on 2019-04-13 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20190413_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentfsc',
            name='coordinator_contact_number',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000000, message='Enter a valid phone number'), django.core.validators.MinValueValidator(1000000000, message='Enter a valid phone number')]),
        ),
    ]
