# Generated by Django 2.1.5 on 2019-04-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20190413_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentfsc',
            old_name='description',
            new_name='tournament_description',
        ),
        migrations.RenameField(
            model_name='tournamentfsc',
            old_name='name',
            new_name='tournament_name',
        ),
        migrations.RenameField(
            model_name='tournamentfsc',
            old_name='venue',
            new_name='tournament_venue',
        ),
    ]
