# Generated by Django 2.1.5 on 2019-04-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_auto_20190413_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentfsc',
            name='age_group',
            field=models.CharField(max_length=100),
        ),
    ]
