# Generated by Django 2.1.5 on 2019-04-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_auto_20190413_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerrankingsms',
            old_name='agegroup',
            new_name='age_group',
        ),
    ]
