# Generated by Django 2.1.5 on 2019-04-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_to_email', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailBody',
        ),
    ]
