# Generated by Django 2.1.5 on 2019-04-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('strong_hand', models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left')], default='RIGHT', max_length=15)),
                ('backhand_style', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('BOTH', 'Both')], default='SINGLE', max_length=20)),
                ('achievements', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('home_club', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('contact_no', models.IntegerField(null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('role_model', models.CharField(max_length=100, null=True)),
                ('cien_no', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
    ]
