# Generated by Django 2.1.5 on 2019-04-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190413_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_no',
        ),
    ]
