# Generated by Django 2.1.5 on 2019-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190420_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
    ]
