# Generated by Django 2.1.5 on 2019-04-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190420_1701'),
        ('users', '0010_auto_20190420_1629'),
    ]

    operations = [
    ]
